/** Verified official / label YouTube IDs. Playback is YouTube embed, not hosted MP3s. */
module.exports = [
  {
    title: "Tujhe Dekha Toh",
    artist: "Kumar Sanu, Lata Mangeshkar",
    album: "Dilwale Dulhania Le Jayenge",
    year: 1995,
    genres: "Bollywood,Romantic",
    youtube_id: "cNV5hLSa9H8",
  },
  {
    title: "Pehla Nasha",
    artist: "Udit Narayan, Sadhana Sargam",
    album: "Jo Jeeta Wohi Sikandar",
    year: 1992,
    genres: "Bollywood,Romantic",
    youtube_id: "Ki41AKu0iHc",
  },
  {
    title: "Tip Tip Barsa Paani",
    artist: "Alka Yagnik, Udit Narayan",
    album: "Mohra",
    year: 1994,
    genres: "Bollywood,Dance,Romantic",
    youtube_id: "BtlnpBb4O8E",
  },
  {
    title: "Jaadu Teri Nazar",
    artist: "Udit Narayan",
    album: "Darr",
    year: 1993,
    genres: "Bollywood,Romantic",
    youtube_id: "n_oP9Onj0r0",
  },
  {
    title: "Chaand Taare",
    artist: "Abhijeet",
    album: "Yes Boss",
    year: 1997,
    genres: "Bollywood,Romantic",
    youtube_id: "N3QzaUwml5w",
  },
  {
    title: "Kuch Kuch Hota Hai",
    artist: "Udit Narayan, Alka Yagnik",
    album: "Kuch Kuch Hota Hai",
    year: 1998,
    genres: "Bollywood,Romantic,Sad",
    youtube_id: "bKZTnnFU9HA",
  },
  {
    title: "Dholna",
    artist: "Lata Mangeshkar, Udit Narayan",
    album: "Dil To Pagal Hai",
    year: 1997,
    genres: "Bollywood,Romantic",
    youtube_id: "bWNkpJdkOj4",
  },
  {
    title: "Aati Kya Khandala",
    artist: "Aamir Khan, Alka Yagnik",
    album: "Ghulam",
    year: 1998,
    genres: "Bollywood,Dance",
    youtube_id: "yIFMTfgJzY0",
  },
  {
    title: "Chaiyya Chaiyya",
    artist: "Sukhwinder Singh, Sapna Awasthi",
    album: "Dil Se..",
    year: 1998,
    genres: "Bollywood,Dance",
    youtube_id: "9yT4F8hzykY",
  },
  {
    title: "Ole Ole",
    artist: "Abhijeet",
    album: "Yeh Dillagi",
    year: 1994,
    genres: "Bollywood,Dance",
    youtube_id: "OhbNVmfdauE",
  },
  {
    title: "O Sanam",
    artist: "Lucky Ali",
    album: "Sunoh",
    year: 1996,
    genres: "Indipop,Romantic,Sad",
    youtube_id: "dWqb-WqbGh8",
  },
  {
    title: "Made in India",
    artist: "Alisha Chinai",
    album: "Made in India",
    year: 1995,
    genres: "Indipop,Dance",
    youtube_id: "IvloHsmi_vg",
  },
  {
    title: "Tunak Tunak Tun",
    artist: "Daler Mehndi",
    album: "Tunak Tunak Tun",
    year: 1998,
    genres: "Indipop,Dance,Bhojpuri",
    youtube_id: "IFP3Jc5ztgg",
  },
];
